### ISSUE TITLE
AppCompatActivity and ActionBarActivity cause null reference exception onCreate(Bundle ....)

### ISSUE THREAD

**Issue by thetempest25** [MvvmCross/MvvmCross#1112]
Hello,

<b>Update</b>
I have recreated this issue in a test repo, No custom code, all packages are latest version and from nuget:
https://github.com/thetempest25/AppCompatTest

< TLDR >
Tried MVVMCross 3.5.2-alpha2 and 4.0.0.0-alpha2, no help, same results.

The problem:
MVVMCross, using the MVVMCross Android Support Library, is not fully loaded when Android displays MainLauncher Activity when using AppCompatActivity or ActionBarActivity as the class root; i.e. android OS tires to display ViewModel before MVVMCross is fully loaded.

The solution:
Make Activity (from Xamarin Android) the root for all Activies, however I can't do this because I lose my support for actionbar and material themeing.

Questions:
1. Any known solutions or possible suggestions?
<i>2. How does MVVMCross ensure that it's loaded before Android OS displays a given View (e.g. 1 - how is MvxApplication.Setup(...) called? && 2 - How does anroidOS wait for MVVMCross to finish loading?)</i>

< Full Version >

I have an odd problem.  I am using MVX 3.5.2-alpha2, Android 4.4 is the target, and I am trying to use AppCompat to get Material Themes into KitKat.  I was using the splash screen activity, and everything was working okay, until I noticed that sometimes, the program would not resume properly from the background.

When the program would resume, one of three things would happen:
1) The program would restart from scratch, e.g. splash screen etc...
2) The program would resume correctly to the proper activity with all information available
3) The program would crash and continually crash, the stacktrace shows that it crashes in Android.Activity.onCreate(Bundle ....)

The crash was coming from the IoC container trying to resolve a BindingStack<T> (no my splash screen doesn't have any bindings; I am aware of that issue).  The problem is that the Container (IoC) was null (e.g. the MVVMCross framework hadn't loaded completely yet...).

I was able to get the crash to happen all of the time by removing the splash screen as the Main Launcher and just using my LoginView as the main launcher.

Future testing shows that the problem occurs when MvxActionBarActivity/EventSource inherit either AppCompat (v7) or ActionBarActivity (v7).  If I make the base class "Activity" everything works properly, of course my actionbar and my themes stop working, but that's to be expected.

I am not sure why the activity isn't waiting for the MVVMCross framework to load when AppCompat/ActionBarActivity are the base class, and yet it forces the Framework to load when "Activity" is the base class.

Here is the stack trace for the error:

```
08-24 17:15:31.513 I/MonoDroid( 2894): UNHANDLED EXCEPTION:
08-24 17:15:31.523 I/MonoDroid( 2894): System.NullReferenceException: Object reference not set to an instance of an object
08-24 17:15:31.523 I/MonoDroid( 2894): at Cirrious.CrossCore.Mvx.Resolve<Cirrious.MvvmCross.Binding.BindingContext.IMvxBindingContextStack`1<Cirrious.MvvmCross.Binding.Droid.BindingContext.IMvxAndroidBindingContext>> () <0x00068>
08-24 17:15:31.523 I/MonoDroid( 2894): at Cirrious.MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContextHelpers.Current<Cirrious.MvvmCross.Binding.Droid.BindingContext.IMvxAndroidBindingContext> () <0x0003f>
08-24 17:15:31.533 I/MonoDroid( 2894): at Cirrious.MvvmCross.Binding.Droid.BindingContext.MvxAndroidBindingContextHelpers.Current () [0x00001] in C:\Users\bmd\Documents\Visual Studio 2015\Projects\MvvmCross-3.5(1)\MvvmCross-3.5\Cirrious\Cirrious.MvvmCross.Binding.Droid\BindingContext\MvxAndroidBindingContextHelpers.cs:17
08-24 17:15:31.533 I/MonoDroid( 2894): at Cirrious.MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (int,Android.Views.ViewGroup,bool) [0x00017] in C:\Users\bmd\Documents\Visual Studio 2015\Projects\MvvmCross-3.5(1)\MvvmCross-3.5\Cirrious\Cirrious.MvvmCross.Binding.Droid\Views\MvxLayoutInflater.cs:109
08-24 17:15:31.533 I/MonoDroid( 2894): at Android.Views.LayoutInflater.n_Inflate_ILandroid_view_ViewGroup_Z (intptr,intptr,int,intptr,bool) [0x00011] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.Views.LayoutInflater.cs:667
08-24 17:15:31.533 I/MonoDroid( 2894): at (wrapper dynamic-method) object.e87cccea-9d6a-4898-9855-fba4c75e836f (intptr,intptr,int,intptr,bool) <IL 0x00023, 0x00047>
08-24 17:15:31.543 I/MonoDroid( 2894): UNHANDLED EXCEPTION:
08-24 17:15:31.543 I/MonoDroid( 2894): System.NullReferenceException: Object reference not set to an instance of an object
08-24 17:15:31.543 I/MonoDroid( 2894): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x0004b>
08-24 17:15:31.543 I/MonoDroid( 2894): at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) [0x00084] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1029
08-24 17:15:31.543 I/MonoDroid( 2894): at Android.App.Activity.OnCreate (Android.OS.Bundle) [0x00070] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2725
08-24 17:15:31.553 I/MonoDroid( 2894): at MvxActionBarEventSourceActivity.OnCreate (Android.OS.Bundle) [0x0000f] in C:\Users\bmd\Documents\Visual Studio 2015\Projects\LaredoPolice\Antares.LaredoPolice.Core\Antares.LaredoPolice.UI.Droid\mvvmcross\MvxActionBarEventSourceActivity.cs:16
08-24 17:15:31.553 I/MonoDroid( 2894): at Antares.LaredoPolice.UI.Droid.Views.LoginView.OnCreate (Android.OS.Bundle) [0x00001] in C:\Users\bmd\Documents\Visual Studio 2015\Projects\LaredoPolice\Antares.LaredoPolice.Core\Antares.LaredoPolice.UI.Droid\Views\LoginView.cs:33
08-24 17:15:31.553 I/MonoDroid( 2894): at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2707
08-24 17:15:31.553 I/MonoDroid( 2894): at (wrapper dynamic-method) object.39236647-7bcf-408d-b0f6-8adffa889a18 (intptr,intptr,intptr) <IL 0x00017, 0x00027>
08-24 17:15:31.553 D/AndroidRuntime( 2894): Shutting down VM
08-24 17:15:31.553 W/dalvikvm( 2894): threadid=1: thread exiting with uncaught exception (group=0xb1cc7b20)
An unhandled exception occured.
```

Here is the code I am using for the Activity and Event Source:

<b>MvxActionBarActivity</b>

```
public class MvxActionBarActivity
    : MvxActionBarEventSourceActivity
    , IMvxAndroidView
{
    public MvxActionBarActivity()
    {
        BindingContext = new MvxAndroidBindingContext(this, this);
        this.AddEventListeners();
    }

    public object DataContext
    {
        get { return BindingContext.DataContext; }
        set { BindingContext.DataContext = value; }
    }

    public IMvxViewModel ViewModel
    {
        get { return DataContext as IMvxViewModel; }
        set
        {
            DataContext = value;
            OnViewModelSet();
        }
    }
    public void MvxInternalStartActivityForResult(Intent intent, int requestCode)
    {
        base.StartActivityForResult(intent, requestCode);
    }

    public IMvxBindingContext BindingContext { get; set; }

    public override void SetContentView(int layoutResId)
    {
        var view = this.BindingInflate(layoutResId, null);
        SetContentView(view);
    }

    protected virtual void OnViewModelSet()
    {
    }

    protected override void AttachBaseContext(Context @base)
    {
        if (this is IMvxAndroidSplashScreenActivity)
        {
            // Do not attach our inflater to splash screens.
            base.AttachBaseContext(@base);
            return;
        }
        base.AttachBaseContext(MvxContextWrapper.Wrap(@base, this));
    }
}
```

<b>MvxActionBarActivityEventSource</b>

```
public abstract class MvxActionBarEventSourceActivity
    : AppCompatActivity //ActionBarActivity  //AppCompatActivity 
    , IMvxEventSourceActivity
{
    protected override void OnCreate(Bundle bundle)
    {
            CreateWillBeCalled.Raise(this, bundle);
        base.OnCreate(bundle);
        CreateCalled.Raise(this, bundle);
    }

    protected override void OnDestroy()
    {
        DestroyCalled.Raise(this);
        base.OnDestroy();
    }

    protected override void OnNewIntent(Intent intent)
    {
        base.OnNewIntent(intent);
        NewIntentCalled.Raise(this, intent);
    }

    protected override void OnResume()
    {
        base.OnResume();
        ResumeCalled.Raise(this);
    }

    protected override void OnPause()
    {
        PauseCalled.Raise(this);
        base.OnPause();
    }

    protected override void OnStart()
    {
        base.OnStart();
        StartCalled.Raise(this);
    }

    protected override void OnRestart()
    {
        base.OnRestart();
        RestartCalled.Raise(this);
    }

    protected override void OnStop()
    {
        StopCalled.Raise(this);
        base.OnStop();
    }

    public override void StartActivityForResult(Intent intent, int requestCode)
    {
        StartActivityForResultCalled.Raise(this, new MvxStartActivityForResultParameters(intent, requestCode));
        base.StartActivityForResult(intent, requestCode);
    }

    protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
    {
        ActivityResultCalled.Raise(this, new MvxActivityResultParameters(requestCode, resultCode, data));
        base.OnActivityResult(requestCode, resultCode, data);
    }

    protected override void OnSaveInstanceState(Bundle outState)
    {
        SaveInstanceStateCalled.Raise(this, outState);
        base.OnSaveInstanceState(outState);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            DisposeCalled.Raise(this);
        }
        base.Dispose(disposing);
    }

    public event EventHandler DisposeCalled;
    public event EventHandler<MvxValueEventArgs<Bundle>> CreateWillBeCalled;
    public event EventHandler<MvxValueEventArgs<Bundle>> CreateCalled;
    public event EventHandler DestroyCalled;
    public event EventHandler<MvxValueEventArgs<Intent>> NewIntentCalled;
    public event EventHandler ResumeCalled;
    public event EventHandler PauseCalled;
    public event EventHandler StartCalled;
    public event EventHandler RestartCalled;
    public event EventHandler StopCalled;
    public event EventHandler<MvxValueEventArgs<Bundle>> SaveInstanceStateCalled;
    public event EventHandler<MvxValueEventArgs<MvxStartActivityForResultParameters>> StartActivityForResultCalled;
    public event EventHandler<MvxValueEventArgs<MvxActivityResultParameters>> ActivityResultCalled;
}
```

Questions:
1. Any known solutions or possible suggestions?
<i>2. How does MVVMCross ensure that it's loaded before Android OS displays a given View (e.g. 1 - how is MvxApplication.Setup(...) called? && 2 - How does anroidOS wait for MVVMCross to finish loading?)</i>

Thank you in advance

**Comment by martijn00** [comment]
Could you try updating to 4.0.0-beta2 because 3.5.2-alpha2 is quite outdated. It might be that we already fixed this.

**Comment by thetempest25** [comment]
I have already upgraded to 4.0.0-beta2 using latest nuget packages, did that today.

I didn't see any breaking changes, however it did not resolve my issue; e.g. same crash, same place.

One question that I have is, how does MVVMCross ensure that it's loaded, on Android, before Android tries to display the view?  When I stepped through the code, onCreate would call MvxSpinner.ctor() which would call some other things, that eventually lead the call of:
<code>
var ioc = Mvx.ResolveSingleton<IMvxIoCProvider>;
var backstack = ioc.Resolve<BackStack<T>>(); // or something like this -- this is where the System.NullReference.Exception is thrown
</code>

Thanks so much for such a fast response!

**Comment by martijn00** [comment]
I couldn't spot a hint on where the error might be yet. Could you create a small repo where i could reproduce this? Other then that you could look into the official app compat example here: https://github.com/MvvmCross/MvvmCross-AndroidSupport/tree/master/Samples

**Comment by thetempest25** [comment]
Hello,

I have created a test app repo that recreates the issue.
https://github.com/thetempest25/Tempest.MvvmCross.AppCompatTest

Sorry it took so long, visual studio kept fighting my with renaming files causing VS to lockup....?...lol never seen that.

Anyways, I know the project is missing "Resources\Values-v21\Styles.xml" because VS won't let me add a file without crashing.

**Comment by thetempest25** [comment]
Okay, repos is commited and ready to be downloaded.

https://github.com/thetempest25/AppCompatTest

**Comment by Cheesebaron** [comment]
Please don't use `<code>` tags around your code, but rather tripple `

**Comment by thetempest25** [comment]
@Cheesebaron Thanks for fixing my code tags!

To answer your questions:
1) I started out the project using MVVMCross 3.5.1; I didn't start using Material Theme & Action Bar.  When I went to add those, I noticed that you guys had an Android Support Lib, but that it required MVVMCross 4, which according to some things I read online, suggested that MVVMCross 4.x had breaking changes in it.  I found the code snippets on the blogs around the web that showed how to get the actionbar without going to MVVMCross 4.
<b>Note: This issue occurs in MVVMCross 4 using the Android Support LIbrary, as well, please see my test repo.</b>
P.S. I have upgraded my own project to MVVMCross 4 and the android support library, again no change, same issue.

2) I had no idea that was not correct (THANK YOU!), I think I saw that somewhere else and just started using it.  I looked it up just now, and have moved the code to inflate the view into onCreate(...).  Unfortunately it does not resolve the issue.
<b>Note:</b> In the stack trace, it's hard to see, but the issue comes in onCreate, it doesn't even get to SetViewModel().  It is calling the inflate & binding code during onCreate() <u>(I suspect) due to global styles that are set in the project.</u> 

<b>Please be advised</b>, I have a global style set for MVXSpinner, and when I step through the code, MVVMCross init's the MVXSpinner, including the bindings, which is what breaks in the above stack trace.

Please see code in:
https://github.com/thetempest25/AppCompatTest
<b>Note: You my repo still has the inflate code in SetViewModel(), moving the code to onCreate()  doesn't resolve this issue.</b>

Please note: I have created a repo that recreates the issue, even if I move the inflate code into onCreate() the issue still persists.


Some things that occur to me

**Comment by thetempest25** [comment]
Some notes about this issue so far:
This issue appears to arise due to the fact that the AppComaptActivity.OnCreate(Bundle bundle), makes a call to the BindingStack (this is of course wrong, because the framework hasn't loaded yet...).  The Framework is loaded after AppComaptActivity.OnCreate(Bundle bundle) via CreateCalled.Raise(this, bundle);

If I put the MvxSplashActivity into the picture, since it forces the framework to load before showing the first viewmodel, it lets the app startup.  However, when the app is resumed from the background (and only sometimes) it get's itself into the same position, trying to make a call to the Mvx Binding framework before the Mvx Framework is loaded.

At this point I am truly baffled and not sure how to proceed.

Any suggestions?

By the way, has anyone had a chance to checkout the test repo and at least confirm they get the same crash?

Thank you very much

**Comment by martijn00** [comment]
It's kind of hard to look into this with the limited time we have. What if you try to run your sample against the real MvvmCross code so you can debug it in there? You might be able to find the cause, and fix it there.

**Comment by diopol** [comment]
Looks I have the same error.

MvvmCross throws exception when restoring MvxAppCompatActivity in case the activity was cleaned up by Android system.

Steps to reproduce: 

1. Create the simplest app with MvvmCross. I use last version 4.0.0 beta3, Xamarin V7 Support version 23.0.1.1, Target API 22.
2. Derive the activity from `MvxAppCompatActivity`. 
3. Set AppCompat theme.
4. In Developer Options on device, check "Don't keep activities" and "Background process limit" to "No background process"
5. Run the app.
6. Press home button on device.
7. Return to the app.

Log:
```
10-12 03:42:25.821: E/AndroidRuntime(20971): FATAL EXCEPTION: main
10-12 03:42:25.821: E/AndroidRuntime(20971): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at dalvik.system.NativeStart.main(Native Method)
10-12 03:42:25.821: E/AndroidRuntime(20971): Caused by: java.lang.reflect.InvocationTargetException
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	... 2 more
10-12 03:42:25.821: E/AndroidRuntime(20971): Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
10-12 03:42:25.821: E/AndroidRuntime(20971): at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x00027>
10-12 03:42:25.821: E/AndroidRuntime(20971): at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) <0x000b3>
10-12 03:42:25.821: E/AndroidRuntime(20971): at Android.App.Activity.OnCreate (Android.OS.Bundle) <0x0014f>
10-12 03:42:25.821: E/AndroidRuntime(20971): at Cirrious.MvvmCross.Droid.Support.AppCompat.MvxEventSourceAppCompatActivity.OnCreate (Android.OS.Bundle) <0x00037>
10-12 03:42:25.821: E/AndroidRuntime(20971): at App1.Droid.Views.MainView.OnCreate (Android.OS.Bundle) <0x00017>
10-12 03:42:25.821: E/AndroidRuntime(20971): at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) <0x00057>
10-12 03:42:25.821: E/AndroidRuntime(20971): at (wrapper dynamic-method) object.44381426-0d88-4e10-8929-f65faf2e458a (intptr,intptr,intptr) <0x00027>
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at md543b3aa6905de4985d1f5ef92a747ffa1.MainView.n_onCreate(Native Method)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at md543b3aa6905de4985d1f5ef92a747ffa1.MainView.onCreate(MainView.java:28)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.Activity.performCreate(Activity.java:5104)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.os.Looper.loop(Looper.java:137)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
10-12 03:42:25.821: E/AndroidRuntime(20971): 	... 5 more
```

The error occurs in `Android.App.Activity.OnCreate` after being called by `MvxEventSourceAppCompatActivity.OnCreate`.

The error doesn't occur when the activity is derived from `MvxActivity`.
The error doesn't occur with `AppCompatActivity` (when MvvmCross is not used).

The sample project may not even have any bindings, let alone fragments.


Tested on:

 - Genymotion API 17
 - Genymotion API 21
 - Samsung Galaxy S3 (GT-I9300, Android 4.3)



View:
```c#
    [Activity(Label = "View for FirstViewModel")]
    public class MainView : MvxAppCompatActivity
    {
        protected  override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            SetContentView(Resource.Layout.FirstView);
        }
    }
```

ViewModel:
```c#
    public class MainViewModel : MvxViewModel
    { 
    }
```

xaml:
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout 
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:local="http://schemas.android.com/apk/res-auto"
      android:orientation="vertical"
      android:layout_width="fill_parent"
      android:layout_height="fill_parent">
      <Button
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:text="Click" />
    </LinearLayout>
```

On my real app this error is very annoying. Even without special developers settings it is often when the user moves out from the app to make a call or anything else, the activity gets cleared and the user can no longer return to its previuos state.

Previously I used MvvmCross 3.5 and derived my activities from `MvxFragmentActivity`. Everything was fine.

**Comment by diopol** [comment]
If I change the Activity.OnCreate to include the following lines, issue no longer occurs.

View:
```c#
    [Activity(Label = "View for FirstViewModel")]
    public class MainView : MvxAppCompatActivity
    {
        protected  override void OnCreate(Bundle bundle)
        {
            // ensure the initialization is done
            var setup = MvxAndroidSetupSingleton.EnsureSingletonAvailable(ApplicationContext);
            setup.EnsureInitialized();

            base.OnCreate(bundle);

            SetContentView(Resource.Layout.FirstView);
        }
    }
```
I just wonder if it is a good solution.

**Comment by Cheesebaron** [comment]
The problem is that you are not using the SplashScreen which MvvmCross usually provides. So when you launch your own activity the MvvmCross subsystem has not initialized. That is why you are getting that NPE.

**Comment by martijn00** [comment]
I guess that is also the problem of @thetempest25 since that example hasn't got a splashscreen either.

**Comment by diopol** [comment]
No, I indeed use the splash screen as it is provided in getting started package. I just didn't show it in the code above.

When app first starts, everything is fine. When app is restored, the splash screen no longer used, thus the issue.

**Comment by slodge** [comment]
The OnCreate of Activities normally go through https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.Droid/Views/MvxActivityViewExtensions.cs#L42 which should cover the case when the SplashScreen isn't shown - that's supposed to help with Rehydration type scenarios and with things like push messages - launch by Intents.

Does MvxAppCompatActivity somehow avoid that?

**Comment by martijn00** [comment]
The extensions are called by `AddEventListeners()` in the Activity:

https://github.com/MvvmCross/MvvmCross/blob/4.0/Cirrious/Cirrious.MvvmCross.Droid/Views/MvxActivity.cs#L34

https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Cirrious.MvvmCross.Droid.Support.AppCompat/MvxAppCompatActivity.cs#L26

The difference i see is that the AppCompat version doesn't have:

protected MvxActivity(IntPtr javaReference, JniHandleOwnership transfer)
            : base(javaReference, transfer)

Which adds that. Could that be the cause?

**Comment by thetempest25** [comment]
@diopol
I used the same solution, ensure framework loaded, but I put it into an override on Create in mvxappcompatactivity

**Comment by kjeremy** [comment]
@martijn00 as far as I know you only need that ctor when instantiating C# objects from the java side so I don't think that's the issue here.  That being said we should probably add that constructor to `MvxAppCompatActivity`.

**Comment by descorp** [comment]
Just my 5 cents: I face the same problem after converting from ActionBarActivity into MvxAppCompatActivity  (#1187). 

@diopol Thanks, you save my day. One quick note : I have to wrap your code into try / catch. Otherwise SplashScreen fires exception in normal start conditions.

```Java
UNHANDLED EXCEPTION:
Cirrious.CrossCore.Exceptions.MvxException: Multiple initialize calls made
```

**Comment by david-laundav** [comment]
Any news regarding this issue? We're still running into this error

**Comment by martijn00** [comment]
Yes, this is fixed in https://github.com/MvvmCross/MvvmCross/pull/1253

**Comment by david-laundav** [comment]
Alright, thanks @martijn00. Do you know which release is this included in? We're currently running 4.1.0.

**Comment by martijn00** [comment]
It was merged on 7 Juni, so i think it is in 4.2.0.
