### ISSUE TITLE
mvx:La.ng in Xamarin.Forms not working

### ISSUE THREAD

**Issue by tomwis** [MvvmCross/MvvmCross#2176]
I have some problems with making mvx:La.ng syntax for Xamarin.Forms working. Finally I downloaded your sample, but it looks like it is not working there too.

### Steps to reproduce

1. Run this sample (I tried it on Android): https://github.com/MvvmCross/MvvmCross/tree/master/TestProjects/Forms/MvxBindings

2. Notice that there is nothing showing for Label in MainPage.xaml, line 33:
`<Label mvx:La.ng="Text ThisIsLocalized" />`

### Expected behavior
Below "Lang Binding" in the app we should see "Localized text" (so text from Text.json for key "ThisIsLocalized").

### Actual behavior
Nothing is showing up below "Lang Binding".

### Configuration

**Version:** 5.1.1 (current master branch)

**Platform:** 
- [ ] iOS
- [x] Android
- [ ] WPF
- [ ] UWP

**Comment by martijn00** [comment]
This is fixed in the Playground.Forms.* samples.

**Comment by StevenBonePgh** [comment]
I am seeing this exact issue using the Playground.Forms samples in 6.0.1 - tested Android and Uwp versions - so I suspect there is still an issue here.  The BindingsPage properly localizes the picker using the `mvx:MvxLang` element but there is nothing shown after the "Lang Binding" label where the following techniques are used:
`<Label Text="{mvx:MvxLang ThisIsLocalizedToo}" />` 
`<Label Text="{mvx:MvxBind TextSource, Mode=OneTime, Converter=Language, ConverterParameter=ThisIsLocalizedThroughMvxBind}" />`
