### ISSUE TITLE
TabLayout inside a nested layout adds the tabs' fragments to the host FragmentManager 

### ISSUE THREAD

**Issue by jandroalvarez** [MvvmCross/MvvmCross#2550]
I've a nested layout for displaying a master-detail layout. On the right side of the screen, I display the detail fragment. This fragment contains a TabLayout. In order to initialize the tabs, I  call MvxNavigationService.Navigate() with the view model of every tab. After this action, the tabs' fragments are properly created.
However, when I pressed back, the FragmentManager.Fragments contains the fragment hosting the master-detail layout and the fragments of all the tabs inside the tablayout. I don't get it because the tabs' fragments have the property AddToBackStack set to false.

### Steps to reproduce :scroll:

1. Create a nested view to represent a master-detail layout. For this, I've followed the playground project containing the NestedView.

```
<LinearLayout
                        android:id="@+id/detail_layout"
                        android:layout_width="0dp"
                        android:layout_height="fill_parent"
                        android:layout_weight="2"
                        android:orientation="vertical"
                        android:layout_marginTop="10dp"
                        android:padding="6dp"
                        local:MvxBind="Visibility Visibility(ConfigurationLoaded)" />
```

```
[MvxFragmentPresentation(FragmentHostViewType = typeof(HostFragment), FragmentContentId = Resource.Id.detail_layout)]
[Register(nameof(DetailFragment ))]
public class DetailFragment : BaseFragment<DetailViewModel>
```

2. Inside the child view, add a TabLayout.

```
 <android.support.design.widget.TabLayout
        android:id="@+id/tabs_detail"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        local:tabMode="fixed"
        local:tabGravity="fill" />
```

3. For every tab, create a Fragment with a MvxTabLayoutPresentation attribute.

```
 [MvxTabLayoutPresentation(TabLayoutResourceId = Resource.Id.tabs_detail, ViewPagerResourceId = Resource.Id.viewpager, Title = "Tab 1")]
    [Register(nameof(TabOneFragment))]
    public class TabOneFragment : BaseFragment<TabOneViewModel>
```
4. Initialize the tab layout from the DetailViewModel

 ```
var tasks = new List<Task>();
tasks.Add(NavigationService.Navigate<TabOneViewModel>());
tasks.Add(NavigationService.Navigate<TabTwoViewModel>());
tasks.Add(NavigationService.Navigate<TabThreeViewModel>());
await Task.WhenAll(tasks);
```

### Expected behavior :thinking:
When tapping back, the SupportFragmentManager should only contain a reference to the host fragment of the nested layout

### Actual behavior :bug:
The SupportFragmentManager contains the host fragment and all the fragments representing the tabs of the TabLayout

### Configuration :wrench:

**Version:** 5.5.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by nmilcoff** [comment]
The fragments collection is not affected by the `AddToBackstack` property. That collection contains all the fragments that are alive at a particular moment.

What happens on the UI when you press back? Do the nested fragment and all the tabs disappear?

It would be great if you could provide us with a small repro case that we can debug.

**Comment by jandroalvarez** [comment]
Hi @nmilcoff 

Forget about the nested layout scenario. The issue is reproduce just having a regular navigation scenario with fragments and no nesting.

In the following repository I've an Android app with a TabLayout whose fragments are still alive after pressing back and coming back to the home view. The fragment containing the tabs is destroyed but the tabs' fragments are alive if you check the list of Fragments at the SupportFragment Manager.

https://github.com/jandroalvarez/MvvmCrossPrototype

**Comment by jandroalvarez** [comment]
Hello @nmilcoff ,

Did you have time for doing any research on this topic?

**Comment by nmilcoff** [comment]
Ouch, sorry. I haven't had much time to take a look at it, I'll do it in the next couple of days and let you know how it goes

**Comment by nmilcoff** [comment]
@jandroalvarez I think this was solved by #2482, we didn't property support `ChildFragmentManager` in 5.6.3. 

I guess that would explain the non-nested version of the issue too, because the tab fragments weren't being added to the host ChildFragmentManager in that case neither.

**Comment by jandroalvarez** [comment]
Hi @nmilcoff 

I've upgraded MvvmCross to 5.6.3 and the issue still remains. 

However, after having read the issue #2482 **I think that I didn't explain myself properly**. 

My main problem is that the nested fragments (OutputOneFragment, OutputTwoFragment and OutputThirteenFragment in the screenshot attached) are added to the Fragments property of SupportFragmentManager but they are never removed, whereas the host fragment was removed.

On the other hand, are you sure that the resolution of the issue #2482 was released on MvvmCross 5.6.3? According to the issue, its milestone v6.0

![supportfragmentmanager](https://user-images.githubusercontent.com/12963327/36474760-cab82e5a-16f8-11e8-8409-89c2664d59ac.PNG)

**Comment by nmilcoff** [comment]
Sorry for the confusion, that code isn't released yet as stable, but it's available in nuget as prerelease.

👍 we'll need to keep investigating.

**Comment by nickrandolph** [comment]
@nmilcoff can you confirm that this issue has been addressed in v6?

**Comment by nmilcoff** [comment]
Unfortunately no @nickrandolph, I think this is still a problem (looking at the source code nothing has changed for a few releases)
